### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MidnightfoxSoren** [hpeinar/planner_v3#18]
**Describe the bug**
Can place building on entire map. It's as though there is a boundary where the buildings wont pass.

**To Reproduce**
Steps to reproduce the behavior in the planner:
1. Click on a building to place
2. try to move around entire map.

**Expected behavior**
I expected to be able to put buildings in places where they are allowed.

**Screenshots**
[Please add screenshots or screen recording for every bug.    
Planner is a visual product and 99% of the issues are visually represented.](url)

**System information (please complete the following information):**
 - Device: desktop
 - OS: windows
 - Browser firefox
 - Version117.0.1 (64 bit)
![Screenshot 2023-09-20 195847](https://github.com/hpeinar/planner_v3/assets/145629402/0bbf0f34-bb4d-4d45-a608-e0ba5f2e1a0c)

**Comment by KaitoPrower** [comment]
Yeah, I just saw there was a V3 and went to use the Four Corners and ran into this issue. From what I can tell, regardless of the chosen map, the available area any items can be placed is based on the size of the Standard Farm map. If it extends any wider or longer than that, placement is stunted...

**Comment by hpeinar** [comment]
@KaitoPrower was right, the viewport was not correctly being resized and thus the events were never handled beyond standard size.

I've fixed the viewport resizing.

Feel free to comment if there are any other issues connected to this.

If you have any other general feedback, ideas or frustrations for the v3 planner, I'm also all ears at henrikpeinar@gmail.com

**Comment by KaitoPrower** [comment]
Thanks, @hpeinar! Seems to be working fine now!
