### ISSUE TITLE
Floors Failing to Erase

### ISSUE THREAD

**Issue by DannyDrito** [hpeinar/planner_v3#30]
**Description**
I can't erase the floors and paths after the April 21, 2024 update. 

**To Reproduce**
1) Place floor/path
2) Select eraser tool
3) Erase floor/path
4) Doesn't work 

**Expected behavior**
Erased floor/paths

**Screenshots**
![Screenshot 2024-04-21 5 58 36 PM](https://github.com/hpeinar/planner_v3/assets/167733383/94b0ac5a-ea90-4ad3-a32b-32cbbd0fa3cc)
![Screenshot 2024-04-21 5 58 29 PM](https://github.com/hpeinar/planner_v3/assets/167733383/04d7513d-9209-4f3f-8ac3-00b1b8dbd830)
![Screenshot 2024-04-21 5 58 18 PM](https://github.com/hpeinar/planner_v3/assets/167733383/21c67e55-b3e0-43eb-9645-d75bbdae8a00)

**System information**
 - Device: Laptop
 - OS: Chrome OS
 - Browser: Chrome
 - Version 117.0.5938.157 (Official Build) (64-bit)

**Comment by Kaylielotl** [comment]
Having the same issue, using Firefox on a Windows 10 PC. Hoping to see this get fixed soon, this seems like a very useful tool.

**Comment by hpeinar** [comment]
Should be fixed now, it was a bug introduced with the latest flooring change logic.
